### ISSUE TITLE
对于资源分配模块，我有地方不太理解。

### ISSUE THREAD

**Issue by gzy147** [revenol/DROO#17]
很抱歉，我对于数字信号传输方面的底层知识掌握有些薄弱。目前我有以下三处不太理解。
1.请问在3.3小节的公式(3)中，用香农公式除以变量Vu的意义是什么？
2.对于每个设备的权重，论文中提到，权重与对应设备的运算速率成正相关。请问设置不同权重的具体意义是什么？是在模拟用户设备本身硬件水平的不同，以及不同设备任务被卸载到边缘服务器后，所得到计算资源量的不同吗？
3.optimiaze.py的代码注释很少。请问在此代码文件中，用于计算a与tau的p1函数与phi函数对应着什么公式或者原理？

**Comment by revenol** [comment]
> 很抱歉，我对于数字信号传输方面的底层知识掌握有些薄弱。目前我有以下三处不太理解。 1.请问在3.3小节的公式(3)中，用香农公式除以变量Vu的意义是什么？ 2.对于每个设备的权重，论文中提到，权重与对应设备的运算速率成正相关。请问设置不同权重的具体意义是什么？是在模拟用户设备本身硬件水平的不同，以及不同设备任务被卸载到边缘服务器后，所得到计算资源量的不同吗？ 3.optimiaze.py的代码注释很少。请问在此代码文件中，用于计算a与tau的p1函数与phi函数对应着什么公式或者原理？

你的问题1&3可以在参考文献【7】中找到答案。
2，每个用户权重是1或者1.5，和速率无关。

**Comment by gzy147** [comment]
感谢您的解答。
不过我还有一点不太明白。如果是这样的话，在计算Q函数时，为不同用户设置不同权重的意义是什么？

**Comment by gzy147** [comment]
> > 很抱歉，我对于数字信号传输方面的底层知识掌握有些薄弱。目前我有以下三处不太理解。 1.请问在3.3小节的公式(3)中，用香农公式除以变量Vu的意义是什么？ 2.对于每个设备的权重，论文中提到，权重与对应设备的运算速率成正相关。请问设置不同权重的具体意义是什么？是在模拟用户设备本身硬件水平的不同，以及不同设备任务被卸载到边缘服务器后，所得到计算资源量的不同吗？ 3.optimiaze.py的代码注释很少。请问在此代码文件中，用于计算a与tau的p1函数与phi函数对应着什么公式或者原理？
> 
> 你的问题1&3可以在参考文献【7】中找到答案。 2，每个用户权重是1或者1.5，和速率无关。


> > 很抱歉，我对于数字信号传输方面的底层知识掌握有些薄弱。目前我有以下三处不太理解。 1.请问在3.3小节的公式(3)中，用香农公式除以变量Vu的意义是什么？ 2.对于每个设备的权重，论文中提到，权重与对应设备的运算速率成正相关。请问设置不同权重的具体意义是什么？是在模拟用户设备本身硬件水平的不同，以及不同设备任务被卸载到边缘服务器后，所得到计算资源量的不同吗？ 3.optimiaze.py的代码注释很少。请问在此代码文件中，用于计算a与tau的p1函数与phi函数对应着什么公式或者原理？
> 
> 你的问题1&3可以在参考文献【7】中找到答案。 2，每个用户权重是1或者1.5，和速率无关。

感谢您的解答。
不过我还有一点不太明白。如果是这样的话，在计算Q函数时，为不同用户设置不同权重的意义是什么？是单纯为了表现实际生产应用中不同用户设备的重要性不同吗？
