### ISSUE TITLE
how to calculate channel gain(input_h)

### ISSUE THREAD

**Issue by dollylly** [revenol/DROO#19]
hi.  I found this paper generated the channe gain from a Rayleigh fading channel model,  and the independent random channel fading factor α  following an exponential distribution with unit mean. 
 
I'd like to ask that in simulation experiment how to calculate the value of channel gain when a random vairable is considered.  Since the random variable following an exponential distribution,  and it hard for me to understand how can we get the value of α in different time slot.  Will it be a specific numerical value or a value choose randomly in the distribution?    Thanks!

**Comment by revenol** [comment]
You want to generate random channel gains. We set the fading factor as a constant, which is an average value and depends on the line-of-sight distance. Please refer to generating random channel samples, i.e., https://www.mathworks.com/matlabcentral/fileexchange/14237-rice-rician-distribution

**Comment by dollylly** [comment]
thank you again! It helps me a lot!
