### ISSUE TITLE
bi-section algorithm details

### ISSUE THREAD

**Issue by pingzhou3** [revenol/DROO#4]
hi, I'm confused with the bisection algorithm applied in the optimization python file. Can you give a detailed explanation or derivation process? It is very important to me. Thanks a lot!

**Comment by revenol** [comment]
The bisection algorithm solves the resource allocation problem, which can be replaced by your own optimization problem. The current bisection algorithm is part of the CD algorithm developed in reference [7]. Please refer to [7] for the details of the bisection algorithm, if necessary.
