### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by QiaomeiHan** [revenol/DROO#5]
Where do the datasets come from?

**Comment by AneeqaMumrez** [comment]
I am unable to view the data sets even. Can you help with that?
Thank you

**Comment by QiaomeiHan** [comment]
> I am unable to view the data sets even. Can you help with that?
> Thank you

For me, I opened the datasets with MATLAB, maybe you can try it. But I still don't know how to get the input, output or other data.

**Comment by revenol** [comment]
> Where do the datasets come from?

 The channels are randomly generated, whose offloading decisions are computed via exhaustive search (one out of 1024 possible combinations for N=10)  or CD algorithm (reference [7]).
 
 Note that it is difficult to enumerate all the possible 2^N actions for N=20 or N=30.
