### ISSUE TITLE
kind of reinforcement learning

### ISSUE THREAD

**Issue by zahraaghapour** [revenol/DROO#6]
hello, 
This reinforcement learning algorithm is which one, off-policy or offline RL?
thank you for the nice paper and your clean code.

**Comment by revenol** [comment]
Off-policy RL.

The training only use data from replay memory without knowledge future data (the time-varying wireless channels in this paper). 

It is difficult to compare two algorithms when all wireless channels are real-time randomly generated. Possibly, repeat your evaluation for multiple times and take the average, which costs huge computations in evaluating the normalized computation rate in equation (11). For the ease of comparison, we pre-generated all data (wireless channels).

**Comment by zahraaghapour** [comment]
Thank you so much for your complete answer.  I have another question I'll open a separate issue for that.
